### ISSUE TITLE
cpp and python implementations of golomb-compressed sequences can produce different results

### ISSUE THREAD

**Issue by lsb** [rasky/gcs#2]
I'd bet it's because of a 32-bit EC2 box that I'm running it on.

For example:

```
for i in {4194303..4194305} ; do
  yes | head -n $i | awk '{print NR}' > numbers
  python ./python/gcs.py build numbers
  mv table.gcs numbers-py.gcs
  ./cpp/gcs build numbers
  mv table.gcs numbers-c.gcs
  md5sum numbers*.gcs
done
```

produces

```
4157a82e59eaaaf5cd40785f71815209  numbers-py.gcs
4157a82e59eaaaf5cd40785f71815209  numbers-c.gcs
```

for ...3, one less than 4_1024_1024;

```
Floating point exception (core dumped)
9368be2ec9755586166ad58744f772ab  numbers-py.gcs
```

for ...4, 4M; and

```
88a0d9cc7ae3213a4d04231e2b18af0e  numbers-py.gcs
66cd6ec6fe5a90fe3ce406b90d4b3e39  numbers-c.gcs
```

for ...5.

I'm getting wildly different sizes: 6069497 for the numbers-py, and 1415 [sic] for numbers-c.

**Comment by rasky** [comment]
Hi, 4_1024_1024-1 is the maximum number of items you can process on a 32-bit computer in the C implementation, if you keep P=1024 (hardcoded in main.cpp).

I've pushed a commit (223b28f) to rework the assert to trigger. Now your example will trigger the assert and abort immediately.

**Comment by lsb** [comment]
Ah, thanks very much.
